### ISSUE TITLE
Defining local workgroup size causes problems with the transform

### ISSUE THREAD

**Issue by zcaudate** [uncomplicate/clojurecl#17]
There are three versions of the same code:

- [one](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj#L14-L48), giving a CL_INVALID_EVENT error. It is reproduced [here](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj#L150-L157)

- [two](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj#L54-L85), giving a CL_INVALID_WORK_GROUP_SIZE error. It is reproduced [here](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj#L160-L167)

- [three](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj#L54-L85), which runs, doesn't give an error, but does nothing to the output. It is reproduced [here](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj#L170-L177)

**Comment by blueberry** [comment]
The code is way too complex for an example. For me to be able to help you, I'd need a short code that calls work-group with explicit numbers that fail. The algorithm you posted might fail due to thousand reasons not related to ClojureCL. All the errors you get originate from the OpenCL driver, not from CloureCL or JOCL.

**Comment by zcaudate** [comment]
The [opencl code](https://github.com/zcaudate-me/image-bench/blob/master/source/opencl/sobel.cl) works with [C++](https://github.com/zcaudate-me/image-bench/blob/master/source/cpp/bench/sobel_benchmark.cpp#L58-L60), on the same call to [clEnqueueNDRangeKernel](https://github.com/opencv/opencv/blob/master/modules/core/src/ocl.cpp#L3076-L3092).

I'm curious for a second opinion because if the problem is not solved, it means that I can't get the speed necessary with clojure on a very basic image filter. The same thing happens on the [grayscale](https://github.com/zcaudate-me/image-bench/blob/master/source/opencl/grayscale.cl) transform as well. If I set `localsize` to `[8, 8]`, I get the same result as what is happening with the `sobel` filter.

**Comment by blueberry** [comment]
I wery well understand that. I'm only saying that the issue is in how you *call* those kernels. The error is very explicit: you're giving invalid work group sizes there. Construct an explicit call that says: launch this kernel with work-size 345x912, 13x3, and I can run that on my machine and perhaps tell you what's happening. Otherwise, I don't see what I can do about this issue.

**Comment by zcaudate** [comment]
I've pushed a version with [tests](https://github.com/zcaudate-me/image-bench/blob/master/test/clojure/image_bench/sobel_test.clj)

running `lein test` will show the following outputs:

```

---- Project (image-bench:1) ----

image-bench.sobel-test

 Failure  [sobel_test.clj:22]
    Info  "running a grayscale kernel at [345, 912] [13, 3]"
    Form  (gray/grayscale img [13 3])
   Check  java.awt.image.BufferedImage
  Actual  clojure.lang.ExceptionInfo: OpenCL error: CL_INVALID_WORK_GROUP_SIZE. {:name "CL_INVALID_WORK_GROUP_SIZE", :code -54, :type :opencl-error, :details "queue"}

 Failure  [sobel_test.clj:39]
    Info  "running a sobel kernel at [345, 912] [13, 3]"
    Form  (sobel/sobel-invalid-work-group-error img [13 3])
   Check  java.awt.image.BufferedImage
  Actual  clojure.lang.ExceptionInfo: OpenCL error: CL_INVALID_WORK_GROUP_SIZE. {:name "CL_INVALID_WORK_GROUP_SIZE", :code -54, :type :opencl-error, :details "queue"}

 Summary (1)
   Files  1
   Facts  4
  Checks  4
  Passed  2
  Thrown  0

 Failed  (2)
```

**Comment by gpu** [comment]
I'm still not well-versed enough in Clojure to pinpoint the error here, but created a **very** basic test at https://github.com/gpu/JOCL/issues/21#issuecomment-364490408 showing that setting the local work size manually is possible, at least. 

A **wild** guess: According to the specification at https://www.khronos.org/registry/OpenCL/specs/opencl-2.2.html#_executing_kernels , there is a constraint:

> If local_work_size is specified and the OpenCL kernel is compiled without non-uniform work-groups enabled, the values specified in global_work_size[0], …, global_work_size[work_dim - 1] **must be evenly divisible** by the corresponding values specified in local_work_size[0], …, local_work_size[work_dim - 1].

Although this did not seem to be necessary in my test, the exact behavior may depend on the underlying OpenCL implementation. So there might be OpenCL implementations that report a `CL_INVALID_WORK_GROUP_SIZE` if this constraint is not met.

Can you log/trace/print the actual *global*- and *local* work sizes of the calls? Maybe one can figure out whether the `CL_INVALID_WORK_GROUP_SIZE` error only appears when they are not evenly divisible.

(Again, it's only a wild guess, but maybe we can successively rule out different possible reasons...)

**Comment by blueberry** [comment]
@gpu work-size works with many variants. I have (successfully) used many variants in my code. Here the problem is probably the specific worksize configuration that the specific opencl drivers do not support, and thus return invalid group size error.

**Comment by zcaudate** [comment]
@gpu, @blueberry:

There is a [test](https://github.com/zcaudate-me/image-bench/blob/master/test/clojure/image_bench/sobel_test.clj#L17-L23) that has local work size divisible into the global work size but it is also failing: https://travis-ci.org/zcaudate-me/image-bench/jobs/339428065#L2158-L2169

I thought that the opencl implementation was OS based. I know that the [cpp version](https://github.com/zcaudate-me/image-bench/blob/master/source/cpp/bench/sobel_benchmark.cpp) runs fine with different local work sizes on my computer so it's a bit of a mystery for me at the moment.

**Comment by blueberry** [comment]
@zcaudate 345 is not divisible with 13. I just picked any random numbers to suggest that test examples should have explicit numbers that fail or pass; not that these numbers are particularly recommended (they are not).

**Comment by zcaudate** [comment]
@blueberry: damn. I thought that was some special debugging parameter.

well it's still failing with a divisible number. like I said before, it's only working with [1 1]

---- Project (image-bench:1) ----
image-bench.sobel-test
nil
 Failure  [sobel_test.clj:22]
    Info  "running a grayscale kernel at [345, 912] [15, 3]"
    Form  (gray/grayscale img [15 3])
   Check  java.awt.image.BufferedImage
  Actual  clojure.lang.ExceptionInfo: OpenCL error: CL_INVALID_WORK_GROUP_SIZE. {:name "CL_INVALID_WORK_GROUP_SIZE", :code -54, :type :opencl-error, :details "queue"}
 Failure  [sobel_test.clj:39]
    Info  "running a sobel kernel at [345, 912] [15, 3]"
    Form  (sobel/sobel-invalid-work-group-error img [15 3])
   Check  java.awt.image.BufferedImage
  Actual  clojure.lang.ExceptionInfo: OpenCL error: CL_INVALID_WORK_GROUP_SIZE. {:name "CL_INVALID_WORK_GROUP_SIZE", :code -54, :type :opencl-error, :details "queue"}

**Comment by blueberry** [comment]
in OpenCL 1.2, it has to be divisible *evenly*, as far as I remember. 345/15 is 23, an odd number. Also, check Apple's opencl specification; there might be additional requirements.

**Comment by zcaudate** [comment]
Does it work on your computer? I'm happy to try and set up an environment that emulates a working version but trying numbers arbitrarily is a waste of time on everybody's part.

```
 Failure  [sobel_test.clj:21]
    Info  "running a grayscale kernel at [1000 1000] [4 4]"
    Form  (gray/grayscale img [4 4])
   Check  java.awt.image.BufferedImage
  Actual  clojure.lang.ExceptionInfo: OpenCL error: CL_INVALID_WORK_GROUP_SIZE. {:name "CL_INVALID_WORK_GROUP_SIZE", :code -54, :type :opencl-error, :details "queue"}
```

**Comment by blueberry** [comment]
@zcaudate Chris, all your tests PASS on my machine. This does not surprise me, since I have an OpenCL 2.0 platform and hardware, which can accept wide range of grid sizes.

As I already said, here the problem is that your platform (Apple supports 1.2, but depending on the machine might be even 1.1) specifies what are valid work group sizes and global sizes, and even their ratios, and you are giving specific numbers that it does not consider valid. This has nothing to do with randomly choosing numbers, but with choosing the valid combination of numbers that makes sense for your problem at hand. This ratio usually has to be even, probably depends on other data that you gather with *info*, and sometimes involves powers of 2. I do not have time to read the spec now, but it's enough information that can help you find what should be used on platforms that you intend to support.

**Comment by zcaudate** [comment]
@blueberry: that's great. that narrows down the options for me. I've been looking at hooking up opencl tests on travis linux boxes, but it's a little hard. Will think about what to do.

**Comment by blueberry** [comment]
That's why I suggested that you start with the *most basic* examles. Something like doubling every number in a buffer. This will help you discover the API, so you know what you are doing and why. Kernels are usually the easier part of a GPU application. What's tricky is how you set up and orchestrate calls to those kernels.

**Comment by blueberry** [comment]
BTW OpenCL si usually not OS dependent, but vendor dependent. Nvidia platform should work the same on Windows and Linux, AMD too. It's a bit different with Apple, since their platform is macOS-only, and covers all hardware from Nvidia, AMD, Intel etc., but with Apple-specific constraints.

**Comment by gpu** [comment]
The observed behavior is still odd. When a certain workgroup size *does* work with C++, it should also work with any additional layer that is wrapped around it (or did I misunderstand or overlook something here?)

**Comment by blueberry** [comment]
@gpu The program is not a 1-1 port, though. First, we would need to look in detail whether the Clojure program does exactly the same thing as the C++ program. That's why I asked for a simple example that demonstrates the problem. Second, it is possible that the C++ version checks the work group and global sizes and adjusts them accordingly. For that, too, the C++ version should be inspected carefully. Unfortunately, I do not have time to learn all specifics of the domains I do not have personal interest in.

I have used various odd combinations of work group and global sizes to doubt that source of this problem is in ClojureCL or JOCL. My first hunch is that Chris would have more success if he starts from simple examples and gradually learn how OpenCL works, rather than plunging into porting a specific image-related algorithms right away.

**Comment by gpu** [comment]
Yes, well, a "1:1 port" is difficult, when OpenCV is involved. It's difficult to compare the setups (different platforms, devices, languages etc...). And it would be helpful to carve out a minimal example that does work in C++ but not in Clojure or Java, but can imagine that it is frustrating when you don't even know in which layer you'd have to start looking...

(I'd give the C++ version a try, but am afraid that the setup might take some time, and even then, there's only a slight chance that I'd figure out what's wrong. At least the actual benchmark is based on CMake ... maybe a chance to actually try out OpenCV, though...).

(I made another guess about something that *might* be wrong at https://github.com/gpu/JOCL/issues/21#issuecomment-364783702 , but that *might* as well be unrelated)

**Comment by gpu** [comment]
@blueberry  This is approaching a "resolved" state, see https://github.com/gpu/JOCL/issues/21#issuecomment-364992773

**Comment by zcaudate** [comment]
@gpu, it'll be great if you can test out the c++ version. I've created a `./run.sh` that should just work.

I'm just happy that the workgroup works as I've been trying to reverse engineer the `canny.cl` kernel from opencv in java and it's been a bit of a challenge so far.

**Comment by gpu** [comment]
I'm currently on Windows, so this `brew install...` thingy will likely not work. But I'm curious, and will at least try to allocate some time for that. I've heard a lot about OpenCV, many of my former colleagues are using it, and I always wanted to give it a try, so this may be an opportunity to do so.

**Comment by zcaudate** [comment]
It's pretty cool but it's getting pretty bloated. I think using MinGW is still the best way to get it working: http://jeanvitor.com/cpp-opencv-windonws10-installing/
